import "@/styles/global.css";
import { Inter } from "next/font/google";
import { Header } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div
          className="fixed bottom-0 left-0 right-0 top-0 z-50 bg-white"
          id="temp-bg-white"
        />
        <div className="flex min-h-[100vh] md:justify-center">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
